spring.application.name=tienda

# Activador dinamico de perfil mediante Maven
spring.profiles.active=@activatedProfile@

server.port=1045
##############################################################

# En desarrollo el "cache" del servidor (false), en producción "true"
spring.thymeleaf.cache=false
#############################################################

# --- Estrictamente debugging ---
# Para eliminar mensajes invasivos de Spring
spring.main.banner-mode=off

# Para definir el formato de despliegue de fecha/hora del log en la consola
logging.pattern.dateformat=hh:mm

# define detalle de logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.type.descriptor.sql.BasicBinder=TRACE

# mostrar queries sql en output
spring.jpa.show-sql=true

# formato a sql para legibilidad
spring.jpa.properties.hibernate.format_sql=true
#############################################################

# --- SQL ---
# hace que springboot corra schema.sql y data.sql en /resources, 
# SOLO ese path y con nomenclatura adecuada para orden, 
# sino hay que declarar manualmente
spring.sql.init.mode=always

# no aborta si falla script sql, en caso de que ya exista bd
spring.sql.init.continue-on-error=true

# - COMPORTAMIENTO SPRING -
# para que hibernate no altere estructura de bd tras leer domain
# spring.jpa.hibernate.ddl-auto=validate 

# para que spring pueda crear tablas desde domain y scripts en resources
spring.jpa.hibernate.ddl-auto=update 
#############################################################

# --- Firebase Storage ---
# Esta información se utiliza para obtener acceso a su storage.
firebase.bucket.name=sc403-93f53.firebasestorage.app
firebase.storage.path=fdpmarket
firebase.json.path=firebase
firebase.json.file=sc403-93f53-firebase-adminsdk-fbsvc-f9e0b18e09.json
#############################################################

# --- Magic Numbers ---
# Limites sistema
sistema.anuncios.maximos-por-vendedor=50
sistema.anuncios.max-imagenes=6

# Reglas Escrow
escrow.dias.entrega-automatica=1
escrow.dias.liberacion-fondos=3
security.session.timeout-minutos=120

# Fees (%)
fees.categoria.oro=0.05
fees.categoria.servicios=0.10
fees.metodo.tarjeta=0.03
#############################################################


# --- SEGURIDAD JWT ---
# lee variable local o usa cadena por defecto
jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}

# milis, 1h = 3600000, 1s = 1000
jwt.expiration.ms=1000
#############################################################


