# Conexion a BD local en mysql
# ?servertime... = define interpretacion de horas a usar
spring.datasource.url=jdbc:mysql://localhost:3306/fdp_market_db?serverTimezone=UTC

# Usuario y clave crearTablas.sql
spring.datasource.username=evaristo
spring.datasource.password=1234

# Driver y comunicacion
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect