# Conexion a BD local en mariadb
# ?servertime... = define interpretacion de horas a usar
spring.datasource.url=jdbc:mariadb://localhost:3306/fdp_market_db?serverTimezone=UTC

# Usuario y clave segun script sql
spring.datasource.username=evaristo
spring.datasource.password=1234

# Driver y comunicacion
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect